
[unlitcampfire]
	#Whether the contained items should be dropped when a campfire goes out by itself or by rain.
	campfireDropsItemsWhenUnlitByTimeOrRain = true
	#Whether the contained items should be dropped when a soul campfire goes out by itself or by rain.
	soulCampfireDropsItemsWhenUnlitByTimeOrRain = true
	#The time (ticks) a soul campfire burns until it goes out by itself. (2000 ticks default; 0 means it burns forever)
	#Range: 0 ~ 10000
	soulCampfireLitTime = 2000
	#Whether a soul campfire should go out when rain falls on it.
	unlitSoulCampfireWithRain = false
	#The time (ticks) a campfire burns until it goes out by itself. (2000 ticks default; 0 means it burns forever)
	#Range: 0 ~ 10000
	campfireLitTime = 2000
	#Whether a campfire should go out when rain falls on it.
	unlitCampfireWithRain = true
	#Whether a campfire should be destroyed when it goes out by itself.
	campfireBreaksWhenUnlitByTime = false
	#Whether a soul campfire should be destroyed when it goes out by itself.
	soulCampfireBreaksWhenUnlitByTime = false

