
[client]
	#Show the durabilityBar indicating ammo count per weapon
	durabilityBar = true

[common]
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	ak47_trigMax = 1
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	microuzi_trigMax = 0
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	ar15hm_trigMax = 0
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	m60_trigMax = 0
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	ak74_trigMax = 1
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	ar15p_trigMax = 0
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	vector45_trigMax = 0
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	m16a1_trigMax = 1
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	m1928_trigMax = 0
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	dp28_trigMax = 1
	#Maximum level of the Trigger Finger enchantment allowed on a weapon
	#Range: 0 ~ 10
	m4_trigMax = 0

